name: Deploy To Artifacts

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The commit ref or SHA'     
        required: true
        default: 'master'
  
  
jobs:
  build:
    if: github.event.deployment.task == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: console.log(context.payload);
  
