name: Request Deployment

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  authenticate:
    runs-on:     ubuntu-latest
    environment: authentication  
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.author_association == 'NONE' }}

    steps:
      - name: Check permissions
        uses: actions/github-script@v3
        with:
          script:  console.log("${{github.event_name}}", context.payload)
  
  request-deploy:
    runs-on: ubuntu-latest
    environment: CI
    needs: authenticate
    if: always() #${{ needs.authenticate.result == 'success' || needs.authenticate.result == 'skipped' }}
    
    steps:
      - name: Request Deployment
        uses: actions/github-script@v3
        with:
          script:  console.log("${{needs.authenticate.result}}")
         
