name: Request Deployment

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  authenticate:
    runs-on:     ubuntu-latest
    environment: authentication  
    #if: ${{ github.event_name == 'pull_request_target' && github.event.author_association == 'NONE' }}

    steps:
      - name: Check permissions
        run: echo ${{github.event_name}} ${{github.event.author_association}}
  
  request-deploy:
    runs-on: ubuntu-latest
    environment: CI
    needs: authenticate
    if: ${{ always() }}
    
    steps:
      - name: Request Deployment
        uses: actions/github-script@v3
        with:
          script:  console.log(context.event_name, context.event)
         
